const menuList = [
  // { name: '主页', code: 'home', childPermissions: null },
  { name: 'demo',
    icon: 'user',
    childPermissions: [
      { key: 'skinDemo', name: '主题色', code: 'skinDemo', icon: 'user' },
      { key: 'localeDemo', name: '多语言', code: 'localeDemo', icon: 'user' },
    ],
  },
  {
    childPermissions: [
      {
        childPermissions: null,
        code: 'UserList',
        id: 4,
        name: '组织与用户管理',
        pid: 1,
        sort: 4,
        type: 1,
        url: '/users',
        icon: 'user',
      },
      {
        childPermissions: null,
        code: 'RoleList',
        id: 5,
        name: '角色管理',
        pid: 1,
        sort: 5,
        type: 1,
        url: '/role',
        icon: 'user',
      },
    ],
    code: 'Group',
    id: 1,
    name: '组织管理',
    pid: -1,
    sort: 1,
    type: 1,
    url: '',
    icon: 'pie-chart',
  },
  {
    childPermissions: [
      {
        childPermissions: null,
        code: 'MonitorList',
        id: 6,
        name: '终端监测',
        pid: 2,
        sort: 6,
        type: 1,
        url: '/monitor',
        icon: 'user',
      },
      {
        childPermissions: null,
        code: 'DeviceManagementList',
        id: 7,
        name: '终端管理',
        pid: 2,
        sort: 7,
        type: 1,
        url: '/deviceManagement',
        icon: 'user',
      },
    ],
    code: 'Device',
    id: 2,
    name: '设备管理',
    pid: -1,
    sort: 2,
    type: 1,
    url: '',
    icon: 'mail',
  },
  {
    childPermissions: [
      {
        childPermissions: null,
        code: 'LogList',
        id: 8,
        name: '日志查询',
        pid: 3,
        sort: 8,
        type: 1,
        url: '/log',
        icon: 'user',
      },
    ],
    code: 'System',
    id: 3,
    name: '系统管理',
    pid: -1,
    sort: 3,
    type: 1,
    url: '',
    icon: 'appstore',
  },
  {
    childPermissions: [
      {
        childPermissions: null,
        code: 'RechargeQueryList',
        id: 28,
        name: '充值查询',
        pid: 27,
        sort: 10,
        type: 1,
        url: '',
        icon: 'user',
      },
    ],
    code: 'ReportForm',
    id: 27,
    name: '报表管理',
    pid: -1,
    sort: 9,
    type: 1,
    url: '',
    icon: 'inbox',
  },
];

/**
 * 根据用户权限获取菜单
 */

export const getMenuList = () => menuList;
